#cloud-config

package_update: true

packages:
    - ufw

runcmd:
    - ufw allow OpenSSH
    - ufw allow 8080
    - ufw --force enable
    - mkdir -p /opt/app
    - printf "APP_PORT=8080\n" > /etc/helloworld.env
    - systemctl restart ssh